### ISSUE TITLE
ライセンスの追加

### ISSUE THREAD

**Issue by fa0311** [takusan23/DeveloperHide#1]
このプロジェクトをForkしたいと考えていますが残念ながらこのプロジェクトにはライセンスがありません。
ライセンスを追加することを検討していただけませんか？

**Comment by takusan23** [comment]
遅くなりました・・・追加しました。
多分問題ないはずなので `Apache-2.0 license` にしました。

**Comment by fa0311** [comment]
ありがとうございます！
